; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
core_dir = D:/pio

[env:desktop-pet]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	-DLV_CONF_INCLUDE_SIMPLE
	-I include
	-I src
	-ID:/pio/packages/framework-arduinoespressif32/libraries/Network/src
extra_scripts = pre:tools/pio_bake_pet.py
lib_ldf_mode = chain
lib_deps = 
	bblanchon/ArduinoJson@^7.3.0
platform_packages = 
	pioarduino/toolchain-xtensa-esp-elf@14.2.0+20260121
	https://github.com/pioarduino/registry/releases/download/0.0.1/esptoolpy-v5.3.0.zip
	https://github.com/pioarduino/registry/releases/download/0.0.1/xtensa-esp-elf-14.2.0_20260121.zip
