[platformio]
core_dir = D:/pio

[env:desktop-pet]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -I src
    -ID:/pio/packages/framework-arduinoespressif32/libraries/Network/src

extra_scripts = pre:../tools/pio_bake_pet.py

lib_ldf_mode = chain

lib_deps =
    bblanchon/ArduinoJson@^7.3.0
